version: '2'
services:
  konfetti_backend:
    environment:
      - NODE_ENV=development
      - RUNS_IN_DOCKER=true
      - JWT_SECRET=shhhhh
      - MAILGUN_API_KEY=
      - MAILGUN_DOMAIN=
      - MAILGUN_FROM=Konfettiapp <noreply@domain.com>
      - BASEURL=http://localhost:3000
      - TWILIO_URL=http://
      - TWILIO_SID=foo
      - TWILIO_KEY=bar
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app
    command: "./node_modules/nodemon/bin/nodemon.js bin/www"
  mongo:
    logging:
      driver: "none"
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data:/data/db